# Generated by Django 3.1.5 on 2021-01-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('blog', '0002_auto_20210106_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='catalog.catalog'),
        ),
    ]
