version: '3.3'
services: 
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    env_file: 
      - ./env_data/authentication.env
    expose:
      - 8000
    volumes:
      - ./authentication:/app
    depends_on: 
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: 
      - ./env_data/api.env
    expose:
      - 8100
    volumes:
      - ./api:/app
    depends_on: 
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file: 
      - ./env_data/front.env
    expose:
      - 8200
    volumes:
      - ./front:/app
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Astra
    ports:
      - 8080:5432
    # volumes:
    #   - ./dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    links:
      - authentication