version: '3.3'
services: 
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - ./authentication:/app
    depends_on: 
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 8100
    volumes:
      - ./api:/app
    depends_on: 
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Astra
    volumes:
      - .dbdata:/var/lib/mysql
    expose:
      - 3306

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    links:
      - authentication
