const ACTIONTYPES = {
    OPEN_PANEL: "OPEN_PANEL",
    OPEN_MODAL: "OPEN_MODAL",
    GET_USER: "GET_USER",
    CLEAR_USER: "CLEAR_USER",
    USER_LOADING: "USER_LOADING",
    CHANGE_USER_DATA: "CHANGE_USER_DATA",
    GET_FULL_CATALOG: "GET_FULL_CATALOG",
    GET_CATALOG: "GET_CATALOG",
}

export default ACTIONTYPES