# Generated by Django 3.1.5 on 2021-01-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('full_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('full_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_catalog.fullcatalog')),
            ],
        ),
    ]
