# Generated by Django 3.1.5 on 2021-01-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('full_catalog', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='full_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_catalog', to='full_catalog.fullcatalog'),
        ),
    ]
