# Generated by Django 3.1.5 on 2021-01-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210110_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='blog',
        ),
    ]
