# Generated by Django 3.1.5 on 2021-01-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
